### ISSUE TITLE
React conference fails

### ISSUE THREAD

**Issue by jaschwar** [ionic-team/starters#1011]
**Starter Type:** .   react
**Starter Template:**  conference

**Description:**

When using Ionic CLI I typed 
`ionic start conference --type=react my-react-conference-app`

**My `ionic info`:**

```
ERROR] Unable to find starter template for my-react-conference-app

        If this is not a typo, please make sure it is a valid starter template
        within the starters repo: https://github.com/ionic-team/starters

**Comment by elylucas** [comment]
Hi @jaschwar,

The command to start a new app using the conference app is:

ionic start myconf conference --type=react

Did you see the other name for the template somewhere?

Thanks
