### ISSUE TITLE
Source path does not exist : resources/android/xml/network_security_config.xml [

### ISSUE THREAD

**Issue by Kowin00** [ionic-team/starters#1033]
Hi everyone,

I'm running this line " ionic cordava platform add android" . and I keep getting this error. Versions are up to date. Do I need to create this xml file? I don't quite understand this part.

Creating Cordova project for the Android platform:
        Path: platforms\android
        Package: com.ionic.app
        Name: Ionic_App
        Activity: MainActivity
        Android target: android-26
Subproject Path: CordovaLib
Android project created with cordova-android@6.3.0
Source path does not exist: resources/android/xml/network_security_config.xml
[ERROR] An error occurred while running subprocess cordova.

**Comment by jairoareyes** [comment]
https://stackoverflow.com/questions/57421889/how-to-solve-source-path-does-not-exist-resources-android-xml-network-security

**Comment by MoAsmar** [comment]
create folder 'xml' inside your app path > resources, and add a file with the name: **network_security_config.xml**
![image](https://user-images.githubusercontent.com/8542126/80920238-892cd080-8d7f-11ea-9fcd-c88eb22dba0f.png)

file should contain the velow xml code:

`<?xml version="1.0" encoding="utf-8"?>
<network-security-config>
<domain-config cleartextTrafficPermitted="true">
    <domain includeSubdomains="true">localhost</domain>
</domain-config>
</network-security-config>`

**Comment by mhartington** [comment]
Closing as this issue is a bit old and may no longer be valid.
