### ISSUE TITLE
Ionic --capacitor have cordova | ionic-native dependencies

### ISSUE THREAD

**Issue by nicearma** [ionic-team/starters#1091]
**Description:**
Why if i generate/start one ionic project with --capacitor i have cordova | ionic-native dependencies?

I think that having new people using ionic with capacitor and find ionic-native in the code/dependencies can be confusing 

**Steps to Reproduce:**

ionic start cap blank --capacitor 

**Output:**

In my package.json i have 

```
"@ionic-native/core": "^5.0.0",
"@ionic-native/splash-screen": "^5.0.0",
"@ionic-native/status-bar": "^5.0.0",

```

**Other Information:**
i don't understand why i have ionic-native dependencies if i want to use capacitor (i know that i can use cordova and ionic-native) and splash-screen and status-bar are already in capacitor plugin.

The same go for the app.component.ts, for me if i want to use capacitor at the base, this should be capacitor imports and not ionic-native

```
import { SplashScreen } from '@ionic-native/splash-screen/ngx';
import { StatusBar } from '@ionic-native/status-bar/ngx';
```

**Comment by Mageek627** [comment]
Also, I think the blank starter should witout `--capacitor` should not have Cordova at all

**Comment by nicearma** [comment]
i think if you go that way, you have to ask if `ionic start blank` have to be in angular, react, vuejs or stenciljs, so the question is having defaults values (angular and capacitor) is necessary 

For me having defaults values help to the not programmers to have one easy way to start one project, but this force the people use some tech more than others. I think that ionic cli should have questions (like angular cli) to help the people chose the tech to use

**Comment by dwieeb** [comment]
@Mageek627 I agree. Aside from the Ionic Native dependencies this issue describes, do the starters have other Cordova stuff I'm not aware of? 

@nicearma The latest Ionic CLI asks which framework to use during `ionic start`.

**Comment by Mageek627** [comment]
@dwieeb To answer your question, here is the complete list of files I found were affected in the Angular blank starter, hopefully I didn't miss any. I'm not familiar with React, so I prefer not to tackle that.

- `package.json` for the ionic-native dependencies
- `src/app/app.module.ts` for the SplashScreen and StatusBar providers
- `src/app/app.component.ts` for the SplashScreen and StatusBar injections and the initializeApp function
- `src/app/app.component.spec.ts` for the statusBarSpy and splashScreenSpy

**Comment by mhartington** [comment]
Resolved!
