### ISSUE TITLE
Suggestion: Stricter compilation flags for starters?

### ISSUE THREAD

**Issue by Mageek627** [ionic-team/starters#1099]
This might be an opinionated choice, but wouldn't it be beneficial for developers to add at least:

```
    "noImplicitAny": true,
    "noImplicitReturns": true,
    "noImplicitThis": true,
    "strictNullChecks": true,
```

in the `tsconfig.json` of starter projects ?

**Comment by Mageek627** [comment]
Related to that, in `starters/angular/official/sidemenu/src/app/app.component.html` with flag `"strictTemplates": true` I get a type error which can be corrected by modifying line 10 with `[detail]="false"`.

Also in `starters/angular/official/sidemenu/src/app/folder/folder.page.ts` with flag `"strictNullChecks": true` we should modify line 10 with `string | null` to compile.

My point is, the generated code with `ionic start` should be strictly typed :)

**Comment by mhartington** [comment]
Since the options are easy enough for people to add themselves/opt-into, I think it's fine not setting them. Not everyone wants all the strictness with TypeScript.
