### ISSUE TITLE
Starter templates' dependencies are very outdated

### ISSUE THREAD

**Issue by Mageek627** [ionic-team/starters#1100]
**Description:**

Starter templates are outdated, for no particular reason (afaik). Why not give developers a chance to be on the latest packages, instead of encouraging them to develop on old versions ?

Furthermore, the current packages have vulnerabilities (according to `npm`):
`found 5 vulnerabilities (3 moderate, 2 high)`

**Steps to Reproduce:**

`ionic start`

**Output:**

```
  "dependencies": {
    "@angular/common": "~8.1.2",
    "@angular/core": "~8.1.2",
    "@angular/forms": "~8.1.2",
    "@angular/platform-browser": "~8.1.2",
    "@angular/platform-browser-dynamic": "~8.1.2",
    "@angular/router": "~8.1.2",
    "@ionic-native/core": "^5.0.0",
    "@ionic-native/splash-screen": "^5.0.0",
    "@ionic-native/status-bar": "^5.0.0",
    "@ionic/angular": "^4.7.1",
    "core-js": "^2.5.4",
    "rxjs": "~6.5.1",
    "tslib": "^1.9.0",
    "zone.js": "~0.9.1"
  },
  "devDependencies": {
    "@angular-devkit/architect": "~0.801.2",
    "@angular-devkit/build-angular": "~0.801.2",
    "@angular-devkit/core": "~8.1.2",
    "@angular-devkit/schematics": "~8.1.2",
    "@angular/cli": "~8.1.2",
    "@angular/compiler": "~8.1.2",
    "@angular/compiler-cli": "~8.1.2",
    "@angular/language-service": "~8.1.2",
    "@ionic/angular-toolkit": "^2.1.1",
    "@types/jasmine": "~3.3.8",
    "@types/jasminewd2": "~2.0.3",
    "@types/node": "~8.9.4",
    "codelyzer": "^5.0.0",
    "jasmine-core": "~3.4.0",
    "jasmine-spec-reporter": "~4.2.1",
    "karma": "~4.1.0",
    "karma-chrome-launcher": "~2.2.0",
    "karma-coverage-istanbul-reporter": "~2.0.1",
    "karma-jasmine": "~2.0.1",
    "karma-jasmine-html-reporter": "^1.4.0",
    "protractor": "~5.4.0",
    "ts-node": "~7.0.0",
    "tslint": "~5.15.0",
    "typescript": "~3.4.3"
  }
```

**My `ionic info`:**

```
Ionic CLI : 5.4.15
```

**Comment by dwieeb** [comment]
@Mageek627 You can find the PRs for updating Angular dependencies with this search: https://github.com/ionic-team/starters/pulls?utf8=%E2%9C%93&q=is%3Apr+is%3Aopen+label%3A%22project+type%3A+angular%22+label%3Adependencies

If there is a particular set of dependencies you think is important, you can comment in the PRs.

As to why some packages are out of date, we're constantly burned by the latest releases having bugs that break the initial experience for Ionic devs. We think reliability is more important for beginners than the bleeding edge. Sometimes we simply forget to update, as well.

**Comment by Mageek627** [comment]
Okay, understandable, bleeding edge is not necessary, but maybe at least not having vulnerabilities would be better for the first impression. I don't know enough about the code base to be able to create a PR for that though. Just giving my (hopefully relevant) feedback.
Cheers
