### ISSUE TITLE
Angular sidemenu: routerDirection ineffective

### ISSUE THREAD

**Issue by manu2504** [ionic-team/starters#1151]
**Starter Type:** angular
**Starter Template:** sidemenu

**Description:**
The AppComponent.html's `routerDirection="root"` property on ion-item that contain the routerLink property, has no effect: when navigating to a page of the menu, we can still go back to the preivous menu item using the browser back button. The navigation is not started from 'root' as expected.

**My `ionic info`:**
```
   Ionic CLI                     : 6.1.0 (/usr/local/lib/node_modules/@ionic/cli)
   Ionic Framework               : @ionic/angular 5.0.0
   @angular-devkit/build-angular : 0.803.25
   @angular-devkit/schematics    : 8.3.25
   @angular/cli                  : 8.3.25
   @ionic/angular-toolkit        : 2.1.2

Utility:
   cordova-res : not installed
   native-run  : not installed

System:
   NodeJS : v10.16.0 (/usr/local/bin/node)
   npm    : 6.13.7
   OS     : macOS High Sierra
```

**Comment by mhartington** [comment]
routerDirection is more about animation and doesn't actually effect router history. You'd want to include `replaceUrl`

```
            <ion-item
              routerLink="/browse"
              routerDirection="root"
              replaceUrl="true"
              routerLinkActive="selected"
            >
```
