### ISSUE TITLE
Suggestion: Split angular imports onto multiple lines

### ISSUE THREAD

**Issue by rtpHarry** [ionic-team/starters#1154]
Countless developer hours around the internet are being wasted with manually reformatting the `inputs` array into multiple lines.

The `providers` already uses the multi-line formatting.

Can we please update this so that we don't have to reformat this every time?

For example:

https://github.com/ionic-team/starters/blob/master/angular/official/tabs/src/app/app.module.ts

```typescript
imports: [BrowserModule, IonicModule.forRoot(), AppRoutingModule],
  providers: [
    StatusBar,
    SplashScreen,
    { provide: RouteReuseStrategy, useClass: IonicRouteStrategy }
  ],
```

Should be:

```typescript
  imports: [
    BrowserModule, 
    IonicModule.forRoot(), 
    AppRoutingModule
  ],
  providers: [
    StatusBar,
    SplashScreen,
    { provide: RouteReuseStrategy, useClass: IonicRouteStrategy }
  ],
```

**Comment by dwieeb** [comment]
Yes, absolutely! I don't think this is done on purpose, rather just organically updated as time went on. Want to send a PR? 💙

**Comment by rtpHarry** [comment]
Ok yes, I'll go through them and put a pr together.
