### ISSUE TITLE
Selected Item class is not updated when browser's navigation features are used

### ISSUE THREAD

**Issue by manu2504** [ionic-team/starters#1166]
**Starter Type:** angular
**Starter Template:** sidemenu

**Description:**
- When navigating to a menu item (e.g. from Inbox to Outbox),
- and going back the previous one via the browser back button feature (e.g. from Outbox to Inbox),
- the selectedItem is not updated (and thus selected class is not applied to the item whose view is displayed) (e.g. Outbox menu item is still highlighted even though the Inbox view is showed). 

**My `ionic info`:**
```
Ionic:

   Ionic CLI                     : 6.1.0 (/usr/local/lib/node_modules/@ionic/cli)
   Ionic Framework               : @ionic/angular 5.0.4
   @angular-devkit/build-angular : 0.803.25
   @angular-devkit/schematics    : 8.3.25
   @angular/cli                  : 8.3.25
   @ionic/angular-toolkit        : 2.2.0

Utility:

   cordova-res : not installed
   native-run  : not installed

System:

   NodeJS : v10.16.0 (/usr/local/bin/node)
   npm    : 6.14.1
   OS     : macOS High Sierra
```

**Comment by mhartington** [comment]
Closed via https://github.com/ionic-team/starters/commit/83ff9dc261be4ed0c6e45706d0b41c79876935e2
