### ISSUE TITLE
Bug: ng build broken for fresh starter apps! 

### ISSUE THREAD

**Issue by bjesuiter** [ionic-team/starters#1193]
**Starter Type:** angular
**Starter Template:** blank (and also tabs, and sidemenu, seems to be a more general problem)
**Integration: Capacitor**

**Description:**
A newly generated ionic4 project with angular is not able to build properly with `ng build`. 
However, `ng serve is fine`. See the exact error message below under 'Other Information'. 
The repo was generated with 
`ionic start --type=angular --capacitor angularCapDemo blank`.

**My `ionic info`:**

```
Ionic:

   Ionic CLI                     : 6.2.1 (/Users/jb-work/.nvm/versions/node/v12.16.1/lib/node_modules/@ionic/cli)
   Ionic Framework               : @ionic/angular 5.0.7
   @angular-devkit/build-angular : 0.803.25
   @angular-devkit/schematics    : 8.3.25
   @angular/cli                  : 8.3.25
   @ionic/angular-toolkit        : 2.2.0

Capacitor:

   Capacitor CLI   : 1.5.2
   @capacitor/core : 1.5.2

Utility:

   cordova-res : not installed
   native-run  : not installed

System:

   NodeJS : v12.16.1 (/Users/jb-work/.nvm/versions/node/v12.16.1/bin/node)
   npm    : 6.13.4
   OS     : macOS Mojave
```

**Other Information:**

The following error happens when building the starter project with `npm run build` (which itself calls `ng build`:

```
CLI:angularCapDemo jb-work$ npm run build

> angularCapDemo@0.0.1 build /Users/jb-work/Develop/test-projects/angularCapDemo
> ng build

Generating ES5 bundles for differential loading...
An unhandled exception occurred: [BABEL] /Users/jb-work/Develop/test-projects/angularCapDemo/www/stencil-ion-app_8-md-entry-js-es2015.js: Could not find plugin "proposal-numeric-separator". Ensure there is an entry in ./available-plugins.js for it. (While processing: "/Users/jb-work/Develop/test-projects/angularCapDemo/node_modules/@babel/preset-env/lib/index.js")
See "/private/var/folders/v0/9g_m7bl15zv17m96kt2k08840000gq/T/ng-QgZidt/angular-errors.log" for further details.
npm ERR! code ELIFECYCLE
npm ERR! syscall spawn
npm ERR! file sh
npm ERR! errno ENOENT
npm ERR! angularCapDemo@0.0.1 build: `ng build`
npm ERR! spawn ENOENT
npm ERR! 
npm ERR! Failed at the angularCapDemo@0.0.1 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/jb-work/.npm/_logs/2020-03-28T09_02_31_951Z-debug.log
CLI:angularCapDemo jb-work$ 
```

Some more background information: 
- The error happens in the starter types: blank, tabs and sidemenu (I didn't test more) 
- Since the error happens in an angular compilation step, it should not be related to using capacitor (even if the --capacitor flag is marked as experimental in the cli)
- The error happens while generating ES5 bundles for differential loading with babel, this is why `ng serve` is not affected.

**Comment by bjesuiter** [comment]
Here is a demo repository for testing: 

https://github.com/bjesuiter/ionic-starter-build-broken

**Comment by bjesuiter** [comment]
I searched a bit more and found out that this seems to be an angular cli problem instead of an ionc starters one. 

One guy from this issue https://github.com/angular/angular-cli/issues/17262
had a helping comment: 

> Try to install "@babel/compat-data": "~7.8.0" to devDependencies. This is the only workaround which helped me.

I can confirm, that this removes the problem for me.  
I updated the demo repository from above. 

However, maybe you should also look into this, since your starter templates are widely used to create new projects and having them broken seems very inconvenient.

**Comment by mhartington** [comment]
Closing as this is no longer valid
