### ISSUE TITLE
Starter template without Angular

### ISSUE THREAD

**Issue by cjorasch** [ionic-team/starters#1213]
**Starter Type:** Stencil
**Starter Template:** blank

**Description:**
It would be great to have a started template for building apps that do not use Angular.

The current documentation does not show how to create an app that just uses Ionic and Stencil.  For many cases this is a great solution without all the additional complexity of Angular.  Most things can be done without it and the app ends up tighter and cleaner.

Developers who have not already been working with Angular will be faced with needing to learn all about Ionic AND Stencil AND Angular just to get started.

**Comment by mhartington** [comment]
Closing for now as we're focusing on supporting Angular, React, Vue
