### ISSUE TITLE
Lighthouse Improvements

### ISSUE THREAD

**Issue by scriptPilot** [ionic-team/starters#1224]
Dear Team,

Thank you for the great piece of code!

To have 100% Lighthouse scores there are missing some files to be created automatically and some improvements. I tested with React / Gallery starter template.

To be managed on developers site, but would be great to have these points fixed out of the box :-)

Lighthouse Report: [React Gallery.pdf](https://github.com/ionic-team/starters/files/4466983/React.Gallery.pdf)

Regards

**Comment by mhartington** [comment]
Closing for now. Thanks for the write up!
