### ISSUE TITLE
ionic1 (official) :: maps :: Cannot load gulp

### ISSUE THREAD

**Issue by esl4m** [ionic-team/starters#1250]
**Starter Type: ionic1
**Starter Template: maps 

**Description:**
[v1] [04:07:34] Cannot load gulp: ReferenceError: primordials is not defined

**My `ionic info`:**
I just run these commands 
`ionic start myApp maps --type=ionic1`
`cd myApp`
`ionic serve`

**Comment by mhartington** [comment]
We no longer provide support for v1 projects. You need to update the latest releases of Angular/React/Vue.
