### ISSUE TITLE
Unable to serve new starter template

### ISSUE THREAD

**Issue by lumkinyun** [ionic-team/starters#1284]
**Starter Type:** ionic-angular
**Starter Template:** blank

**Description:**
Not able to serve a new project using `ionic start`.
Cannot GET /   while serving with `ionic serve`. The command shows ERROR in ./src/global.scss. Error: Failed to find '@ionic/angular/css/core.css'

![image](https://user-images.githubusercontent.com/58815221/82398060-8242d500-9a84-11ea-993a-5b11b0a970b4.png)

If clean up everything in global.scss, it can serve properly.
Had tried `npm i node-sass postcss-loader css-loader sass-loader` and `npm update`. Also tried removing the node_modules and `npm install` again. I even removed and reinstalled `npm install -g @ionic/cli`. The outcome remains the same. 

Please help. Thank you.

**My `ionic info`:**

```
Ionic:

   Ionic CLI                     : 6.9.2 (C:\Users\Lum Kin Yun\AppData\Roaming\npm\node_modules\@ionic\cli)
   Ionic Framework               : @ionic/angular 5.1.1
   @angular-devkit/build-angular : 0.901.6
   @angular-devkit/schematics    : 9.1.6
   @angular/cli                  : 9.1.6
   @ionic/angular-toolkit        : 2.2.0

Capacitor:

   Capacitor CLI   : 2.1.0
   @capacitor/core : 2.1.0

Utility:

   cordova-res : not installed
   native-run  : not installed

System:

   NodeJS : v12.16.1 (C:\Program Files\nodejs\node.exe)
   npm    : 6.13.4
   OS     : Windows 10
```

**Comment by mhartington** [comment]
Hi there! I'm going to close this as I am unable to replicate this.
