### ISSUE TITLE
Blank template contains IonHeader inside IonContent

### ISSUE THREAD

**Issue by danaugrs** [ionic-team/starters#1357]
It's not documented anywhere what adding an `IonHeader` inside `IonContent` does. What is the reason for it? Let's either remove it if there is no reason or document it.

https://github.com/ionic-team/starters/blob/f2774c8d4979821945f0250a50b867d184c44cc2/react/official/blank/src/pages/Home.tsx#L15-L19

**Comment by devinshoemaker** [comment]
From what I have tested, it’s to support the newer header style for iOS. I agree though, there could be some better documentation around it.
