### ISSUE TITLE
[ERROR] Unable to find starter template for maps - 3.20.0

### ISSUE THREAD

**Issue by mattezell** [ionic-team/starters#145]
**Starter Type:** built-in
**Starter Template:** maps

**Description:**
```
matt@matt-ubuntu-7577:~/w$ lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 16.04.4 LTS
Release:	16.04
Codename:	xenial
matt@matt-ubuntu-7577:~/w$ node -v
v8.11.1
matt@matt-ubuntu-7577:~/w$ npm -v
5.6.0
matt@matt-ubuntu-7577:~/w$ ionic -v
3.20.0
matt@matt-ubuntu-7577:~/w$ ionic start ionicClean20180507Maps maps
✖ Looking up starter - failed!
[ERROR] Unable to find starter template for maps

        If this is not a typo, please make sure it is a valid starter template 
        within the starters repo: https://github.com/ionic-team/starters

matt@matt-ubuntu-7577:~/w$ 
```

**My `ionic info`:**
n/a - project fails to generate based on ionic 'maps' starter

**Other Information:**
Let me know if I am missing anything...

**Edit**: Not that this is an open issue - just sharing for reference.

**Comment by dwieeb** [comment]
@mattezell Unfortunately the maps starter does not exist for the latest version of Ionic Framework. You can see available starters with `ionic start --list`. To start an app with legacy Ionic v1, use `--type=ionic1`.

Here is the full command:

```
ionic start ionicClean20180507Maps maps --type=ionic1
```
