### ISSUE TITLE
Generated page module has `FormsModule` should be optional

### ISSUE THREAD

**Issue by Lindsor** [ionic-team/starters#1506]
We should be able to choose between
`FormsModule`, `ReactiveFormsModule`, `NONE` in the schematics when generating module

Current Example:
```
import { NgModule } from '@angular/core';
import { CommonModule } from '@angular/common';
import { FormsModule } from '@angular/forms';

import { IonicModule } from '@ionic/angular';

import { AccountsPageRoutingModule } from './accounts-routing.module';

import { AccountsPage } from './accounts.page';

@NgModule({
  imports: [
    CommonModule,
    FormsModule,
    IonicModule,
    AccountsPageRoutingModule
  ],
  declarations: [AccountsPage]
})
export class AccountsPageModule {}
```

Example with `NONE`:
```
import { NgModule } from '@angular/core';
import { CommonModule } from '@angular/common';

import { IonicModule } from '@ionic/angular';

import { AccountsPageRoutingModule } from './accounts-routing.module';

import { AccountsPage } from './accounts.page';

@NgModule({
  imports: [
    CommonModule,
    IonicModule,
    AccountsPageRoutingModule,
  ],
  declarations: [AccountsPage],
})
export class AccountsPageModule {}
```

**Comment by mhartington** [comment]
Pull requests are always welcomed! 

Generally though, I'm not really a fan of this idea. As the process of adding an import statement is not really difficult. 
And with the already existing options, adding yet another to accomplish something that could be done rather quickly doesn't seem to be the right call.

**Comment by Lindsor** [comment]
I agree adding an import is not a huge deal. My concern is more on your assuming i want FormsModule vs ReactiveForms module.

Per your argument you shouldn't assume anything at all and not include either (which I'm also ok with).

Right now my process of generating a new page is:
`npx ionic g page <name>`

Open: name.module.ts
delete `FormsModule`

Open: name.component.ts
add `ChangeDetectionStrategy.OnPush`

Open: name.spec.ts
cleanup some deprecated fucntions

This is all easy and doable. Just defeats the purpose of a CLI if theres this much manual work. And i dont want to have to manage juniors making sure they are doing everything above.
FYI (the 2 other steps are unrelated to this issue, issue opened somewhere else).

I do plan on creating a PR for all of these just want to make sure its aligned with you guys

**Comment by SimonBrazell** [comment]
I don't think `FormsModule` or `ReactiveFormsModule` should be included by default at all, they aren't required for every page, I remove them from more pages than I use them in, but yeah as @mhartington says, not difficult to import, or remove as needed.

**Comment by mhartington** [comment]
Going to close that. Since the default is good enough for most people, I don't want to change the default experience.
