### ISSUE TITLE
Difference between ion-menu and ion-side-menus

### ISSUE THREAD

**Issue by TakhirMamirov** [ionic-team/starters#1529]
I'm new to Ionic and trying to add a left-side menu to the web app. It shall work on mobiles as well.

When I firstly tried to add **_ion-menu_**, it displayed, but disappears after I click second time on a certain menu item.
Then I went to sources here and figured out there **_ion-side-menus_** exists. I put in on the page and it started appearing all the time, as needed, although when I hit F12 in browser and check mobile view, it's gone.

Which of those shall I use to permanently display on a desktop web page and act as needed in mobile sliding menu?

**Comment by mhartington** [comment]
Hi there! It appears this isn't really an issue, and more of a question, so Im going to close this. Please check out the [forum](https://forum.ionicframework.com) as this is a better place for questions. Thanks!
