### ISSUE TITLE
ionic start myApp aws says [ERROR] Unable to find starter template for aws

### ISSUE THREAD

**Issue by ramki12** [ionic-team/starters#1662]
Iam just trying to follwo the README
"ionic start myApp aws " gives error
 [ERROR] Unable to find starter template for aws

 If this is not a typo, please make sure it is a valid starter template within the starters repo:
        https://github.com/ionic-team/starters

Can someone pls help

**Comment by mhartington** [comment]
The AWS template only exists fo the older V3 framework starters and not the latest Angular/React/Vue projects.
