### ISSUE TITLE
Angular Starter(Side Menu) ion-router-outlet not updating after route change

### ISSUE THREAD

**Issue by abhibly** [ionic-team/starters#167]
**Starter Type:** angular 
**Starter Template:** side menu

**Description:**

Hello i tried the angular starter for side menu here https://github.com/ionic-team/starters/tree/master/angular/official/sidemenu . The App is correctly activating the defualt route(home).If i click on list route in sidemenu the url gets changed but the content is not changing. Can you please tell me whether it is known issue or am i missing something?
**My `ionic info`:**

```
cli packages: (C:\Users\Shiva\AppData\Roaming\npm\node_modules)

    @ionic/cli-utils  : 1.19.2
    ionic (Ionic CLI) : 3.20.0

System:

    Node : v8.9.4
    npm  : 5.6.0
    OS   : Windows 10

Misc:

    backend : legacy
```

**Other Information:**

Thanks in advance, Abhilash

**Comment by mhartington** [comment]
Hi! This is was an issue with the current alpha that the starters ship with. Please run

```
npm install @ionic/angular@4.0.0-alpha.6 --save --save-exact
```

This should be fixed in that release.

I will update the starters package.json
Thanks!

**Comment by abhibly** [comment]
@mhartington Thank you... It is working fine now
