### ISSUE TITLE
"docs" link goes to v2 documentation

### ISSUE THREAD

**Issue by royappa** [ionic-team/starters#1688]
**Starter Type:** ionic-angular
**Starter Template:** sidemenu

**Description:**
In the "Home" page, the "docs" link goes to http://ionicframework.com/docs/v2  instead of ionic 5 docs.

**Comment by jcesarmobile** [comment]
ionic-angular template uses ionic 3, should go to v3 docs, not to v5 docs (nor v2 docs, but v2 redirect to v3)

**Comment by liamdebeasi** [comment]
Thanks! This was fixed via https://github.com/ionic-team/starters/pull/1690.
