### ISSUE TITLE
feat: RxJS 7+ support on Ionic/Angular default template.

### ISSUE THREAD

**Issue by Sampath-Lokuge** [ionic-team/starters#1723]
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already include this feature request, without success.

### Describe the Feature Request

Hi,
I have created a new Ionic/ Angular(14) app. But still, it has  "rxjs": "~6.6.0",.

### Describe the Use Case

Angular 14 supports RxJS 7+ now.

### Describe Preferred Solution

This new RxJS is so much better and smaller. So we would like to have it with the default template.

**Comment by liamdebeasi** [comment]
We should probably update the dependency. Would you like to contribute and put up a PR for this change? I'd be happy to review it.

The work involved should be to change this line to use version `~7.5.0`: https://github.com/ionic-team/starters/blob/main/angular/base/package.json#L23

This is the same version that ships with an Angular app created with `ng new`.

**Comment by mhamri** [comment]
more than rxjs 7 need to be updated 
https://github.com/ionic-team/ionic-framework/issues/26011
