### ISSUE TITLE
Vue starter should use vite instead of vue cli

### ISSUE THREAD

**Issue by elycheikhsmail** [ionic-team/starters#1739]
Vue starter should use vite instead of vue cli
as you know vue is maintance mode and vite is the new way of building vue apps in vue ecosystem (and maybe most js frontend) for this raisons I inspect ionic-vue to be based on vite as main tools for dev and prod.

**Comment by liamdebeasi** [comment]
Thanks for the report. Ionic CLI v7 now ships Vue starters with Vite, so I am going to close this.
