### ISSUE TITLE
CommonModule missing in angular-standalone blank starter

### ISSUE THREAD

**Issue by marlon-ionic** [ionic-team/starters#1783]
**Starter Type:** angular-standalone
**Starter Template:** blank

**Description:**
`src/app/home/home.page.ts` doesn't import CommonModule, so common directives like `ngIf` or `ngFor`, and common pipes like `async` are not available.

**My `ionic info`:**

```
Ionic:

   Ionic CLI                     : 7.1.1 (/Users/marlon/.volta/tools/image/packages/@ionic/cli/lib/node_modules/@ionic/cli)
   Ionic Framework               : @ionic/angular 7.0.5
   @angular-devkit/build-angular : 15.2.8
   @angular-devkit/schematics    : 15.2.8
   @angular/cli                  : 15.2.8
   @ionic/angular-toolkit        : 9.0.0

Capacitor:

   Capacitor CLI      : 5.0.2
   @capacitor/android : 5.0.3
   @capacitor/core    : 5.0.2
   @capacitor/ios     : 5.0.3

Utility:

   cordova-res : not installed globally
   native-run  : 1.7.2

System:

   NodeJS : v18.14.1 (/Users/marlon/.volta/tools/image/node/18.14.1/bin/node)
   npm    : 9.3.1
   OS     : macOS Unknown
```

**Other Information:**

Also created https://github.com/ionic-team/starters/pull/1782 if that helps.

**Comment by sean-perkins** [comment]
Hello 👋 I'm going to close this based on our conversation on the PR here: https://github.com/ionic-team/starters/pull/1782

Angular developers should either import the specific directives that they are requiring for their template or they can import the "legacy" `CommonModule` if they want a simpler experience at the cost of a minimal bundle size increase.
