### ISSUE TITLE
Upgrade vue starter to vue@^3.3.0

### ISSUE THREAD

**Issue by mrleblanc101** [ionic-team/starters#1813]
**Starter Type:** vue
**Starter Template:** all

**Description:**
Upgrade starter to vue 3.3.

**Comment by liamdebeasi** [comment]
Hey there,

The Vue starter uses the caret ("^") in its `package.json` which means your package manager will install the latest minor release of Vue. So even though the version listed is `3.2.47`, the `^` at the beginning will cause Vue 3.3 to be installed.
