### ISSUE TITLE
confirmSignIn function requires 3 arguments, but gets 2. 

### ISSUE THREAD

**Issue by marcosantonocito** [ionic-team/starters#250]
**Starter Type:** ionic-angular
**Starter Template:** official/aws

**Description:**
I just tried this starter following the README instructions but I get this error:

typescript: src/pages/confirmSignIn/confirmSignIn.ts, line: 25 
Expected 3 arguments, but got 2. 

```
confirm() {
    Auth.confirmSignIn(this.user, this.code)
    .then(() => this.navCtrl.push(TabsPage))
```

**My `ionic info`:**

```
cli packages: (/usr/local/lib/node_modules)

    @ionic/cli-utils  : 1.19.2
    ionic (Ionic CLI) : 3.20.0

global packages:

    cordova (Cordova CLI) : 8.0.0 

local packages:

    @ionic/app-scripts : 3.1.10
    Cordova Platforms  : none
    Ionic Framework    : ionic-angular 3.9.2

System:

    ios-deploy : 1.9.2 
    Node       : v8.9.3
    npm        : 6.1.0 
    OS         : macOS High Sierra
    Xcode      : Xcode 9.4 Build version 9F1027a 

Environment Variables:

    ANDROID_HOME : not set

Misc:

    backend : pro
```

**Other Information:**

Now the function confirmSignIn requires 3 arguments: user, code and mfaType. In this starter there isn't the mfaType argument.

More info here:
https://aws.github.io/aws-amplify/media/authentication_guide.html#sign-in

**Comment by alexapam** [comment]
I was able to get past this point by doing the following:
1. In AWS Console > AWS Mobile Hub, open the User Pool configuration for your project
2. In User Pool, set the 'MFA and verifications' settings so that MFA is "optional"
3. In ConfirmSignInPage class change code to pass an empty string:
`
public mfaType: string = ""; 

confirm() {
    Auth.confirmSignIn(this.user, this.code, this.mfaType)
      .then(() => this.navCtrl.push(TabsPage))
      .catch(err => logger.debug('confirm error', err));
  }`
