### ISSUE TITLE
Uncaught Exception[Object Object] using Graphql in Appsync with AWS Amplify in Ionic AWS Starter Template

### ISSUE THREAD

**Issue by rishabhtech1994** [ionic-team/starters#254]
**Starter Type:** ionic start myApp aws
**Starter Template:**  AWS Starter Templete 

**Description:**

When I started using the AWS Template of Ionic, The AWS Amplify Library does not include the Graphql Modules in the beginning, I Updated the AWS Amplify Library using "npm install aws-amplify@latest". After this whenever i am using API.Graphql function, it is showcasing the below error. I have already checked the documentation but it is showing nothing extra apart from this. Please help me out on this. Stuck !!

This is my function which is a Query i need to pass this query inside my Graphql function as stated in AWS Amplify Documentation. But it is returning Uncaught Exception[Object Object].

**My `ionic info`:**

cli packages: (C:\Users\Madhav\AppData\Roaming\npm\node_modules)

    @ionic/cli-utils  : 1.19.2
    ionic (Ionic CLI) : 3.20.0

global packages:

    cordova (Cordova CLI) : 8.0.0

local packages:

    @ionic/app-scripts : 3.1.9
    Cordova Platforms  : android 7.0.0
    Ionic Framework    : ionic-angular 3.9.2

System:

    Node : v9.4.0
    npm  : 5.6.0
    OS   : Windows 10

Environment Variables:

    ANDROID_HOME : not set

Misc:

    backend : pro

![screenshot 89](https://user-images.githubusercontent.com/34940017/41702584-510b21fc-754e-11e8-8dae-760ae4f716c3.png)

**Comment by haverchuck** [comment]
@rishabhtech1994 

Can you the API.graphql calls and the GraphQLOperation objects you are passing in?  That would be helpful in looking at this issue.

**Comment by wataruoguchi** [comment]
I don't think it's ionic's issue. I'm seeing the same issue with AppSync + Vue.js. Oddly Firefox displays this error but Chrome doesn't. I bet you can close this issue.
