### ISSUE TITLE
No auth token refresh routine

### ISSUE THREAD

**Issue by kszpirak** [ionic-team/starters#31]
This starter is quite useless to be honest if you are looking for an app which will implement persistent login. **Cognito tokens expire after 1 hour.** After that token and identityID becomes null. Refreshing the token is not implemented here. When the token is refreshed the IdentityId remains null. This app, the way it is implemented has killed countless hour of my time and 2 other developers. No one can seem to figure out how to do this correctly. I wish someone from AWS finally provided a code here to show how refresh is correctly and how "background token refresh" is handled when the user turns off the app or simply puts in the background.

**Comment by richardzcode** [comment]
Hey @kszpirak the aws starter is updated with the latest aws-amplify. It won't have the null identityId issue. Do you want to have a try? Thanks!
