### ISSUE TITLE
ZIP FILE Error Ionic + AWS Zip File: missing: snapshotID or fileContentsList

### ISSUE THREAD

**Issue by innovazz** [ionic-team/starters#35]
When trying to import the zip file to AWS, I receive the following upload error:

missing: snapshotID or fileContentsList

**Comment by richardzcode** [comment]
Hey @innovazz the latest aws starter is built upon aws-amplify, which you don't need to import zip file. Instructions here: https://github.com/ionic-team/starters/tree/master/ionic-angular/official/aws

Thanks!
Richard
