### ISSUE TITLE
aws_cognito_region is not defined

### ISSUE THREAD

**Issue by knro** [ionic-team/starters#36]
When running ionic serve, the server starts and this message is displayed. I check src/assets/aws-config.jw and it defined aws_cognito_region:

const 'aws_cognito_region' = 'us-west-2';

Screenshot for the error is attached.

![screenshot_20180124_222756](https://user-images.githubusercontent.com/5986347/35352701-dc99a59e-0155-11e8-93bc-0c34c7369370.png)

**Comment by richardzcode** [comment]
Hey @knro the aws starter is updated with aws-amplify. It doesn't have this issue.

**Comment by dwieeb** [comment]
Yes, I believe with @richardzcode's changes, this issue can be closed. Let me know if I'm mistaken!
