### ISSUE TITLE
Icons are not showing up angular sidemenu starter

### ISSUE THREAD

**Issue by rohitkrishna12** [ionic-team/starters#383]
**Starter Type:** angular
**Starter Template:** Sidemenu

**Description:**
ion-icons are not showing up in the angular sidemenu starter templates

**My `ionic info`:**
Ionic:

   ionic (Ionic CLI)          : 4.0.1 (C:\Users\KrishnaK\AppData\Roaming\npm\node_modules\ionic)
   Ionic Framework            : @ionic/angular 4.0.0-beta.0
   @angular-devkit/core       : 0.7.0-rc.3
   @angular-devkit/schematics : 0.7.0-rc.3
   @angular/cli               : 6.0.8
   @ionic/ng-toolkit          : 1.0.0
   @ionic/schematics-angular  : 1.0.1

Cordova:

   cordova (Cordova CLI) : 8.0.0
   Cordova Platforms     : android 7.0.0

System:

   Android SDK Tools : 26.1.1
   NodeJS            : v8.11.3 (C:\Program Files\nodejs\node.exe)
   npm               : 5.6.0
   OS                : Windows 10

Environment:

   ANDROID_HOME : C:\Android\android-sdk

**Other Information:**

**Comment by siva563** [comment]
Actually it is working fine in ionic serve -l, but it is not working in real device, I was tried.. any help from your side.

**Comment by mhartington** [comment]
Closing as this issue is old and no longer valid
