### ISSUE TITLE
AWS Mobile CLI Init Issue - Is There Another Way To Config?

### ISSUE THREAD

**Issue by appliedsine** [ionic-team/starters#387]
**Starter Type:** 
**Starter Template:** 

**Description:**

After awsmobile init -

backend awsmobile project creation error
the security token included in the request is invalid
{ UnrecognizedClientException: The security token included in the request is invalid ....

I recognize that this is an aws cli issue, I have set modified config multiple times credentials, environment variables, created users, etc., 

I am wondering if there is a way to configure the aws backend manually with a config file or a large hammer?  

**My `ionic info`:**

```
<paste here>
```

**Other Information:**

**Comment by mhartington** [comment]
Closing as this issue is old and may no longer be valid.
