### ISSUE TITLE
Use cordova-plugin-ionic-keyboard for starters ?

### ISSUE THREAD

**Issue by jrmlt** [ionic-team/starters#41]
The current ionic-plugin-keyboard is broken for me at least with the cordova-plugin-ionic-webview while building using with latest xcode 9.X. (fixed elements going out of view when keyboard is opened, webview scrolling while disableScroll is activated, etc.)
While trying to reproduce using the ionic-conference-app, I couldn't because this project is using another keyboard plugin "cordova-plugin-ionic-keyboard" which solves all my issues.

Why is there two plugins keyboard from ionic ? Is there a deprecated one ?

Thanks in advance for the feeback.

**Comment by dwieeb** [comment]
Yes, I think it is time to activate the new keyboard plugin by default. `ionic-plugin-keyboard` should be deprecated.

Thanks @jrmlt!

@manucorporat @mhartington FYI
