### ISSUE TITLE
cordova-plugin-statusbar not installed

### ISSUE THREAD

**Issue by KiwiKilian** [ionic-team/starters#430]
**Starter Type:** angular, ionic-angular (only checked those)
**Starter Template:** tabs (only checked this one)

**Description:**
The npm package `@ionic-native/status-bar` is installed ([ionic-angular](https://github.com/ionic-team/starters/blob/master/ionic-angular/base/package.json#L25), [angular](https://github.com/ionic-team/starters/blob/master/angular/base/package.json#L25)) and also a method is called in [app.component.ts](https://github.com/ionic-team/starters/blob/master/ionic-angular/official/tabs/src/app/app.component.ts#L18) but the plugin `cordova-plugin-statusbar` is not installed in [config.xml](https://github.com/ionic-team/starters/blob/master/integrations/cordova/config.xml) and also not the NPM package.
Leaving you with those warnings:
```
console.warn: Ionic Native: tried calling StatusBar.hide, but the StatusBar plugin is not installed. 
console.warn: Install the StatusBar plugin: 'ionic cordova plugin add cordova-plugin-statusbar' 
```

**Comment by dwieeb** [comment]
Fixed with https://github.com/ionic-team/starters/commit/fd33401eb4924bd332833c57ead4d48b4c7f11e1

Thank you!
