### ISSUE TITLE
Adding “tabs” to “blank” starter

### ISSUE THREAD

**Issue by chriskwanmy** [ionic-team/starters#44]
I have set up a blank starter using 
ionic start myApp blank

Now if I want to add tabs to the bottom part of the app. So what should I do except starting a new app using tabs starter?

**Comment by dwieeb** [comment]
@chriskwanmy Let's reserve this repo for features/suggestions/bugs on the starters. For general Ionic support questions, please see our [Support Page](https://ionicframework.com/support).

Thanks!
