### ISSUE TITLE
starter template

### ISSUE THREAD

**Issue by kpsNaveenJoel** [ionic-team/starters#45]
unable to find starter template for project

**Comment by dwieeb** [comment]
@kpsNaveenJoel Can you tell me what this is? If it's an error you're getting, can you tell me how you got it?

**Comment by BitBruce** [comment]
@dwieeb They might be referring to a starter not appearing on this page: https://market.ionicframework.com/starters/

I didn't see the AWS one on here but found it when creating an app with Ionic Pro.
