### ISSUE TITLE
? Where is your project's distribution directory that stores build artifacts:  dist  

### ISSUE THREAD

**Issue by tanzeelrana** [ionic-team/starters#51]
? Where is your project's distribution directory that stores build artifacts:  dist 

shouldnt this be www ? ?

**Comment by dwieeb** [comment]
Not sure what you're asking. Build artifacts are not committed to git.

You can learn how this repo works in the CONTRIBUTING.md file: https://github.com/ionic-team/starters/blob/master/CONTRIBUTING.md

**Comment by msegers** [comment]
I know this is an old question @dwieeb but I believe he's asking why the output directory of this starter is /dist. While the documentation describes /www as the output directory. I was a bit confused by this as well since I was reflecting a project's structure with this starter app.
