### ISSUE TITLE
Ionic 4 - RouterModule not used - remove import?

### ISSUE THREAD

**Issue by peterennis** [ionic-team/starters#542]
@dwieeb 

**Starter Type:** 
angular
**Starter Template:** 
tabs

**Description:**

RouterModule not used

**My `ionic info`:**

```
C:\ae\adaept.com\aetabs>ionic info
√ Gathering environment info - done!

Ionic:

   ionic (Ionic CLI)             : 4.3.0 (C:\Users\peter\AppData\Roaming\npm\node_modules\ionic)
   Ionic Framework               : @ionic/angular 4.0.0-beta.15
   @angular-devkit/build-angular : 0.8.5
   @angular-devkit/schematics    : 0.8.5
   @angular/cli                  : 6.2.5
   @ionic/angular-toolkit        : 1.1.0





System:

   NodeJS : v8.12.0 (C:\Program Files\nodejs\node.exe)
   npm    : 6.4.1
   OS     : Windows 10


C:\ae\adaept.com\aetabs>
```

**Other Information:**

![capture430](https://user-images.githubusercontent.com/140737/47948216-da89a480-dee9-11e8-9eb0-0634e9f65e4c.png)
![capture429](https://user-images.githubusercontent.com/140737/47948217-da89a480-dee9-11e8-9578-d7883b67ca0b.png)
![capture428](https://user-images.githubusercontent.com/140737/47948218-da89a480-dee9-11e8-86d1-105ba5dab8ee.png)

**Comment by mhartington** [comment]
Closing
