### ISSUE TITLE
ionic 4 - should update angular tabs template

### ISSUE THREAD

**Issue by c350156378** [ionic-team/starters#583]
**Starter Type:** angular 
**Starter Template:**  tabs 

**Description:**
the tabs starter still got white screen due to the closed issue #15438, as the current tabs starter has not been updated. i updated the tabs starter manually as stated in 4.0.0-beta.18 (2018-12-13) changelog, and it works fine.

**@ionic/angular version**
```
"@ionic/angular": "^4.0.0-beta.19",
```

**Comment by dwieeb** [comment]
Our starters lock in the framework version:
https://github.com/ionic-team/starters/blob/3eff71b76db5afe597d20b2c9a8baa5bd3bddd38/angular/base/package.json#L26

Here is the PR for updating to beta.19: https://github.com/ionic-team/starters/pull/582
