### ISSUE TITLE
Starter pack tabs @ionic/angular: 4.0.0-beta.19 uses wrong dependencies.

### ISSUE THREAD

**Issue by mvandenbrink** [ionic-team/starters#593]
**Starter Template:** 
tabs

**Description:**
After using the ionic command to start a new ionic 4 project with the start template tabs I got npm warnings that the ionic 4.0.0-beta.19 requires a peer of @angular 7.1.3

**My `ionic info`:**

```
Ionic:

   ionic (Ionic CLI)             : 4.5.0 (C:\.......\AppData\Roaming\npm\node_modules\ionic)
   Ionic Framework               : @ionic/angular 4.0.0-beta.19
   @angular-devkit/build-angular : 0.10.7
   @angular-devkit/schematics    : 7.0.7
   @angular/cli                  : 7.0.7
   @ionic/angular-toolkit        : 1.2.0

System:

   NodeJS : v8.11.4 (C:\.....\nodejs\node.exe)
   npm    : 6.0.1
   OS     : Windows 10
```

**Other Information:**

npm WARN @ionic/angular@4.0.0-beta.19 requires a peer of @angular-devkit/core@^7.1.2 but none is installed. You must install peer dependencies yourself.
npm WARN @ionic/angular@4.0.0-beta.19 requires a peer of @angular-devkit/schematics@^7.1.2 but none is installed. You must install peer dependencies yourself.
npm WARN @ionic/angular@4.0.0-beta.19 requires a peer of @angular/core@^7.1.3 but none is installed. You must install peer dependencies yourself.
npm WARN @ionic/angular@4.0.0-beta.19 requires a peer of @angular/common@^7.1.3 but none is installed. You must install peer dependencies yourself.
npm WARN @ionic/angular@4.0.0-beta.19 requires a peer of @angular/forms@^7.1.3 but none is installed. You must install peer dependencies yourself.
npm WARN @ionic/angular@4.0.0-beta.19 requires a peer of @angular/router@~7.1.3 but none is installed. You must install peer dependencies yourself.
npm WARN @ionic/angular@4.0.0-beta.19 requires a peer of @angular/compiler@^7.1.3 but none is installed. You must install peer dependencies yourself.
npm WARN @ionic/angular@4.0.0-beta.19 requires a peer of @angular/compiler-cli@^7.1.3 but none is installed. You must install peer dependencies yourself.
npm WARN @ionic/angular@4.0.0-beta.19 requires a peer of @angular/platform-browser@^7.1.3 but none is installed. You must install peer dependencies yourself.
npm WARN @ionic/angular@4.0.0-beta.19 requires a peer of @angular/platform-browser-dynamic@^7.1.3 but none is installed. You must install peer dependencies yourself.

**Comment by dwieeb** [comment]
This is fixed, thanks!
