### ISSUE TITLE
sidemenu doesn't demonstrate list items using Angular's Router

### ISSUE THREAD

**Issue by marckassay** [ionic-team/starters#603]
**Starter Type:** angular
**Starter Template:** sidemenu

**Description:**
After installing sidemenu with angular type, the list items do not have any functionality.

**My `ionic info`:**
```
Ionic:

   ionic (Ionic CLI)             : 4.6.0
   Ionic Framework               : @ionic/angular 4.0.0-rc.0
   @angular-devkit/build-angular : 0.11.4
   @angular-devkit/schematics    : 7.1.4
   @angular/cli                  : 7.1.4
   @ionic/angular-toolkit        : 1.2.2

Cordova:

   cordova (Cordova CLI) : not installed
   Cordova Platforms     : android 7.1.4
   Cordova Plugins       : no whitelisted plugins (0 plugins total)

System:

   Android SDK Tools : 26.1.1 (C:\Users\marck\AppData\Local\Android\Sdk)
   NodeJS            : v10.13.0 (C:\Program Files\nodejs\node.exe)
   npm               : 1.10.1
   OS                : Windows 10
```

**Other Information:**
I created a [demo starter](https://github.com/marckassay/IonicV4AngularV7Starter) that adds functionality to the list items mentioned above. Although this is my first success understanding Angular's Router, hopefully it can be used in some way to have a working starter demonstrating usage for Router.

**Comment by mhartington** [comment]
Closing as the sidemenu starter has been updated since this isssue was opened.
