### ISSUE TITLE
Ionic4 - uses wrong dependencies

### ISSUE THREAD

**Issue by kponda** [ionic-team/starters#642]
**Starter Type:**  angular
**Starter Template:** base

**Description:**

ionic start generated package.json uses wrong dependencies
 * @angular/*
* @ionic-native/*

https://github.com/ionic-team/starters/blob/master/angular/base/package.json

https://github.com/ionic-team/ionic/blob/ad0c8a4e5c3f7f917a262c4a9e85bf4a7eaf6caf/angular/package.json

** ionic info **

Ionic:

   ionic (Ionic CLI)             : 4.9.0 (/Users/kat/.nvm/versions/node/v10.14.1/lib/node_modules/ionic)
   Ionic Framework               : @ionic/angular 4.0.0
   @angular-devkit/build-angular : 0.11.4
   @angular-devkit/schematics    : 7.1.4
   @angular/cli                  : 7.1.4
   @ionic/angular-toolkit        : 1.2.2

System:

   NodeJS : v10.14.1 (/Users/kat/.nvm/versions/node/v10.14.1/bin/node)
   npm    : 6.4.1
   OS     : macOS Mojave

**Comment by dwieeb** [comment]
Thanks!

**Comment by kponda** [comment]
Ultra fast!!
Thank you!
