### ISSUE TITLE
angular tabs: avoid absolute redirects to root path in child module

### ISSUE THREAD

**Issue by nharrer** [ionic-team/starters#682]
**Starter Type: angular**
**Starter Template: tabs**

**Description:**
The redirects at the end of [tabs.router.module.ts](../blob/master/angular/official/tabs/src/app/tabs/tabs.router.module.ts) are absolute:
```
      {
        path: '',
        redirectTo: '/tabs/tab1',
        pathMatch: 'full'
      }
    ]
  },
  {
    path: '',
    redirectTo: '/tabs/tab1',
    pathMatch: 'full'
}
```
Which is not wrong per se and works in this example. But wouldn't it be better if they were relative like this?
```
      {
        path: '',
        redirectTo: 'tab1',
        pathMatch: 'full'
      }
    ]
  },
  {
    path: '',
    redirectTo: 'tabs',
    pathMatch: 'full'
  }
```

Otherwise it stops working if the module is used in any path other then the root path. Which happened here: https://forum.ionicframework.com/t/ionic-4-redirect-to-tabs-page/157314

_(I know, it's a really minor thing)._

**Comment by robertnicjoo** [comment]
This absolutely works, i was getting dizzy over this issue.

Thank you so much <3 .

**Comment by prince-vishal** [comment]
Hi, My when moving from a child tab route `/tabs/profile` to `/qr-code` , when I press the back button on `/qr-code`. I am redirected to `/tabs/home`

This is my tabs-routing.module.ts

`{
        path: 'tabs',
        component: TabsPage,
        children: [
            {
                path: 'home',
                loadChildren: () => import('../home/pages/home_page/homepage.module').then(m => m.HomePageModule)
            },
            {
                path: 'search',
                loadChildren: () => import('../search-page/search.module').then(m => m.SearchPageModule),
                pathMatch: 'full'

            },
            {
                path: 'transactions',
                loadChildren: () => import('../transaction/pages/transactions_page/transactions.module').then(m => m.TransactionsPageModule),
                pathMatch: 'full'

            },
            {
                path: 'create',
                loadChildren: () => import('../create/create.module').then(m => m.CreatePageModule),
                pathMatch: 'full'

            },
            {
                path: 'profile',
                loadChildren: () => import('../user/pages/profile/profile.module').then(m => m.ProfilePageModule),
                pathMatch: 'full'

            },
        ]
    },
    {
        path: '',
        redirectTo: '/tabs',
        pathMatch: 'full'
    }`
