### ISSUE TITLE
Cannot find type definition file 

### ISSUE THREAD

**Issue by ashishsoni** [ionic-team/starters#69]
getting below error with IONIC 3

typescript: node_modules/aws-amplify/lib/PubSub/Providers/MqttOverWSProvider.d.ts, line: 1 
            Cannot find type definition file for 'paho-mqtt'. 

       L1:  import { Client } from 'paho-mqtt';
       L2:  import * as Observable from 'zen-observable';

[12:58:05]  typescript: node_modules/aws-amplify/lib/PubSub/Providers/MqttOverWSProvider.d.ts, line: 2 
            Cannot find type definition file for 'zen-observable'. 

       L1:  import { Client } from 'paho-mqtt';
       L2:  import * as Observable from 'zen-observable';
       L3:  import { AbstractPubSubProvider } from './PubSubProvider';

[12:58:05]  typescript: node_modules/aws-amplify/lib/PubSub/Providers/PubSubProvider.d.ts, line: 1 
            Cannot find type definition file for 'zen-observable'. 

       L1:  import * as Observable from 'zen-observable';
       L2:  import { PubSubProvider, ProvidertOptions } from '../types';

[12:58:05]  typescript: node_modules/aws-amplify/lib/PubSub/PubSub.d.ts, line: 1 
            Cannot find type definition file for 'zen-observable'. 

       L1:  import * as Observable from 'zen-observable';
       L2:  import { PubSubProvider, PubSubOptions, ProvidertOptions } from './types';

[12:58:05]  typescript: node_modules/aws-amplify/lib/PubSub/types/Provider.d.ts, line: 1 
            Cannot find type definition file for 'zen-observable'. 

       L1:  import * as Observable from 'zen-observable';
       L2:  import { ProvidertOptions } from './PubSub';

**Comment by dwieeb** [comment]
@ashishsoni Let's reserve this repo for features/suggestions/bugs on the starters. For general Ionic support questions, please see our [Support Page](https://ionicframework.com/support).

Thanks!
