### ISSUE TITLE
Error: Can't resolve './app.module.ngfactory' in producation mode

### ISSUE THREAD

**Issue by myemuk** [ionic-team/starters#7]
Hello,
to produce an error I just uses the following commands:

ionic start testApp
cd testApp/
ionic cordova build android --release --prod

Error description:
Error: ./src/app/main.ts
Module not found: Error: Can't resolve './app.module.ngfactory' in '/home/user/tmpfs/testApp/src/app'                                                     
resolve './app.module.ngfactory' in '/home/user/tmpfs/testApp/src/app'
  using description file: /home/user/tmpfs/testApp/package.json (relative path: ./src/app)                                                                
    Field 'browser' doesn't contain a valid alias configuration
  after using description file: /home/user/tmpfs/testApp/package.json (relative path: ./src/app)                                                          
    using description file: /home/user/tmpfs/testApp/package.json (relative path: ./src/app/app.module.ngfactory)                                         
      no extension
        Field 'browser' doesn't contain a valid alias configuration
        /home/user/tmpfs/testApp/src/app/app.module.ngfactory doesn't exist
      .ts
        Field 'browser' doesn't contain a valid alias configuration
        /home/user/tmpfs/testApp/src/app/app.module.ngfactory.ts doesn't exist
      .js
        Field 'browser' doesn't contain a valid alias configuration
        /home/user/tmpfs/testApp/src/app/app.module.ngfactory.js doesn't exist
      .json
        Field 'browser' doesn't contain a valid alias configuration
        /home/user/tmpfs/testApp/src/app/app.module.ngfactory.json doesn't exist
      as directory
        /home/user/tmpfs/testApp/src/app/app.module.ngfactory doesn't exist
[/home/user/tmpfs/testApp/src/app/app.module.ngfactory]
[/home/user/tmpfs/testApp/src/app/app.module.ngfactory.ts]
[/home/user/tmpfs/testApp/src/app/app.module.ngfactory.js]
[/home/user/tmpfs/testApp/src/app/app.module.ngfactory.json]
[/home/user/tmpfs/testApp/src/app/app.module.ngfactory]
 @ ./src/app/main.ts 2:0-60
    at BuildError.Error (native)
    at new BuildError (/home/user/tmpfs/testApp/node_modules/@ionic/app-scripts/dist/util/errors.js:16:28)
    at callback (/home/user/tmpfs/testApp/node_modules/@ionic/app-scripts/dist/webpack.js:121:28)
    at emitRecords.err (/home/user/tmpfs/testApp/node_modules/webpack/lib/Compiler.js:269:13)
    at Compiler.emitRecords (/home/user/tmpfs/testApp/node_modules/webpack/lib/Compiler.js:375:38)
    at emitAssets.err (/home/user/tmpfs/testApp/node_modules/webpack/lib/Compiler.js:262:10)
    at applyPluginsAsyncSeries1.err (/home/user/tmpfs/testApp/node_modules/webpack/lib/Compiler.js:368:12)
    at next (/home/user/tmpfs/testApp/node_modules/tapable/lib/Tapable.js:218:11)
    at Compiler.compiler.plugin (/home/user/tmpfs/testApp/node_modules/webpack/lib/performance/SizeLimitsPlugin.js:99:4)
    at Compiler.applyPluginsAsyncSeries1 (/home/user/tmpfs/testApp/node_modules/tapable/lib/Tapable.js:222:13)

**Comment by myemuk** [comment]
cli packages: (/usr/local/lib/node_modules)

    @ionic/cli-utils  : 1.18.0
    ionic (Ionic CLI) : 3.18.0

global packages:

    cordova (Cordova CLI) : 7.1.0 

local packages:

    @ionic/app-scripts : 3.1.0
    Cordova Platforms  : android 6.3.0 browser 5.0.1
    Ionic Framework    : ionic-angular 3.9.2

System:

    Android SDK Tools : 26.1.1
    Node              : v6.11.5
    npm               : 5.5.1 
    OS                : Linux 4.10

Environment Variables:

    ANDROID_HOME : /home/user/.Android/SDK

Misc:

    backend : legacy

**Comment by rakshans1** [comment]
Same issue for me

**Comment by dwieeb** [comment]
Hi @myemuk, please see https://github.com/ionic-team/ionic-app-scripts/issues/1309
