### ISSUE TITLE
Can not run "npm run tsc"

### ISSUE THREAD

**Issue by yanchaosb123** [ionic-team/starters#72]
**Starter Type:** 
**Starter Template:** 

**Description:**

when I download the code and try to compile it  using "npm run tsc", I found these compilation errors.

> @ tsc G:\Code\js\starters
> tsc

src/commands/build.ts:25:9 - error TS2416: Property 'getMetadata' in type 'BuildCommand' is not assignable to the same property in base type 'Command'.
  Type '() => Promise<{ name: string; description: string; inputs: { name: string; description: string; }...' is not assignable to type '() => Promise<CommandMetadata<CommandMetadataInput, CommandMetadataOption>>'.
    Type 'Promise<{ name: string; description: string; inputs: { name: string; description: string; }[]; }>' is not assignable to type 'Promise<CommandMetadata<CommandMetadataInput, CommandMetadataOption>>'.
      Type '{ name: string; description: string; inputs: { name: string; description: string; }[]; }' is not assignable to type 'CommandMetadata<CommandMetadataInput, CommandMetadataOption>'.
        Property 'summary' is missing in type '{ name: string; description: string; inputs: { name: string; description: string; }[]; }'.

25   async getMetadata() {
           ~~~~~~~~~~~


src/commands/deploy.ts:20:9 - error TS2416: Property 'getMetadata' in type 'DeployCommand' is not assignable to the same property in base type 'Command'.
  Type '() => Promise<{ name: string; description: string; options: ({ name: string; description: string;...' is not assignable to type '() => Promise<CommandMetadata<CommandMetadataInput, CommandMetadataOption>>'.
    Type 'Promise<{ name: string; description: string; options: ({ name: string; description: string; defau...' is not assignable to type 'Promise<CommandMetadata<CommandMetadataInput, CommandMetadataOption>>'.
      Type '{ name: string; description: string; options: ({ name: string; description: string; default: stri...' is not assignable to type 'CommandMetadata<CommandMetadataInput, CommandMetadataOption>'.
        Property 'summary' is missing in type '{ name: string; description: string; options: ({ name: string; description: string; default: stri...'.

20   async getMetadata() {
           ~~~~~~~~~~~

src/index.ts:7:9 - error TS2416: Property 'getMetadata' in type 'StartersNamespace' is not assignable to the same property in base type 'Namespace'.
  Type '() => Promise<{ name: string; description: string; }>' is not assignable to type '() => Promise<NamespaceMetadata>'.
    Type 'Promise<{ name: string; description: string; }>' is not assignable to type 'Promise<NamespaceMetadata>'.
      Type '{ name: string; description: string; }' is not assignable to type 'NamespaceMetadata'.
        Property 'summary' is missing in type '{ name: string; description: string; }'.

7   async getMetadata() {
          ~~~~~~~~~~~


src/index.ts:16:46 - error TS2345: Argument of type 'this' is not assignable to parameter of type 'Namespace'.
  Type 'StartersNamespace' is not assignable to type 'Namespace'.
    Types of property 'getMetadata' are incompatible.
      Type '() => Promise<{ name: string; description: string; }>' is not assignable to type '() => Promise<NamespaceMetadata>'.
        Type 'Promise<{ name: string; description: string; }>' is not assignable to type 'Promise<NamespaceMetadata>'.
          Type '{ name: string; description: string; }' is not assignable to type 'NamespaceMetadata'.
            Property 'summary' is missing in type '{ name: string; description: string; }'.

16       ['build', async () => new BuildCommand(this)],
                                                ~~~~


src/index.ts:17:48 - error TS2345: Argument of type 'this' is not assignable to parameter of type 'Namespace'.

17       ['deploy', async () => new DeployCommand(this)],
                                                  ~~~~


src/index.ts:25:9 - error TS2554: Expected 1 arguments, but got 3.

25   await execute(ns, pargv, env);
           ~~~~~~~~~~~~~~~~~~~~~~~

npm ERR! code ELIFECYCLE
npm ERR! errno 2
npm ERR! @ tsc: `tsc`
npm ERR! Exit status 2
npm ERR!
npm ERR! Failed at the @ tsc script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\DavidStark\AppData\Roaming\npm-cache\_logs\2018-04-04T00_52_02_036Z-debug.log

**My `ionic info`:**

cli packages: (C:\Users\DavidStark\AppData\Roaming\npm\node_modules)

    @ionic/cli-utils  : 1.19.2
    ionic (Ionic CLI) : 3.20.0

System:

    Node : v8.9.0
    npm  : 5.5.1
    OS   : Windows 10

Misc:

    backend : pro

 typescript@2.8.1

```
<paste here>
```

**Other Information:**

**Comment by yanchaosb123** [comment]
tsc --version 
Version 2.6.1

**Comment by dwieeb** [comment]
@yanchaosb123 Sorry about that, please pull down my latest commit, `npm install`, and try again.
