### ISSUE TITLE
Starters for CLI 4

### ISSUE THREAD

**Issue by peterennis** [ionic-team/starters#75]
@dwieeb 

I am testing CLI 4 rc1 and some issues are reported fixed.
Where do I find the basic starter (or others if they exist yet) so I can see the new additions
and continue testing?

**Comment by dwieeb** [comment]
Ionic Angular 4+ starters are listed here: https://github.com/ionic-team/starters/tree/master/angular/official

See readme for more info: https://github.com/ionic-team/starters#starters

**Comment by peterennis** [comment]
Thanks!
