### ISSUE TITLE
No resource found that matches the given name (at 'networkSecurityConfig' with value '@xml/network_security_config')

### ISSUE THREAD

**Issue by douglasgsouza** [ionic-team/starters#758]
**Starter Type:** angular
**Starter Template:** sidemenu

**Description:**
After commit a11d861, when i run command `ionic cordova run android` the error appears: 

```
cmd: Command failed with exit code 1 Error output:
[cordova]  xxxx\platforms\android\res\xml\config.xml:34:53-81: AAPT: No resource found that matches the given name (at 'networkSecurityConfig' with value '@xml/network_security_config').
[cordova]
[cordova] xxxx\platforms\android\build\intermediates\res\merged\debug\xml\config.xml:34: error: Error: No resource found that matches the given name (at 'networkSecurityConfig' with value '@xml/network_security_config').
[cordova]
[cordova]
[cordova]
[cordova]  FAILURE: Build failed with an exception.
[cordova]  * What went wrong:
[cordova]  Execution failed for task ':processDebugResources'.
[cordova]  > com.android.ide.common.process.ProcessException: Failed to execute aapt

```

**My `ionic info`:**

```
Ionic:

   ionic (Ionic CLI)             : 4.12.0 (C:\Users\XXXX\AppData\Roaming\npm\node_modules\ionic)
   Ionic Framework               : @ionic/angular 4.4.0
   @angular-devkit/build-angular : 0.13.9
   @angular-devkit/schematics    : 7.3.9
   @angular/cli                  : 7.3.9
   @ionic/angular-toolkit        : 1.5.1

Cordova:

   cordova (Cordova CLI) : 9.0.0 (cordova-lib@9.0.1)
   Cordova Platforms     : android 6.3.0
   Cordova Plugins       : cordova-plugin-ionic-keyboard 2.1.3, cordova-plugin-ionic-webview 4.0.1, (and 4 other plugins)

System:

   Android SDK Tools : 26.1.1 (C:\android-sdk)
   NodeJS            : v10.14.0 (C:\Program Files\nodejs\node.exe)
   npm               : 6.4.1
   OS                : Windows 10

```

**Other Information:**

**Comment by dwieeb** [comment]
Uh oh! 

@douglasgsouza Did the `resources/android/xml/network_security_config.xml` file get created? I'm not running into this issue with new apps. I'm using cordova-android 8.0.0 (I noticed you're on 6.3.0, could that be it?).

**Comment by douglasgsouza** [comment]
Yes @dwieeb, resources/android/xml/network_security_config.xml has been created.
I started new project today with these steps:

```
ionic start myApp sidemenu
ionic cordova prepare android
```

edited config.xml widget id

run
`ionic cordova run android`.
And the error appeared.

P.S:
After reporting this problem, I changed my config.xml this way:
```
 <edit-config file="AndroidManifest.xml" mode="merge" target="/manifest/application" xmlns:android="http://schemas.android.com/apk/res/android">
            <application android:networkSecurityConfig="@xml/network_security_config" />
        </edit-config>
        <resource-file src="resources/android/xml/network_security_config.xml" target="res/xml/network_security_config.xml" />
```
And Successful Launch App

**Comment by moiniyan** [comment]
This is the way to go,

After reporting this problem, I changed my config.xml this way:

 <edit-config file="AndroidManifest.xml" mode="merge" target="/manifest/application" xmlns:android="http://schemas.android.com/apk/res/android">
            <application android:networkSecurityConfig="@xml/network_security_config" />
        </edit-config>
        <resource-file src="resources/android/xml/network_security_config.xml" target="res/xml/network_security_config.xml" />
And Successful Launch App

**Comment by dwieeb** [comment]
I can confirm this is an issue with older versions of `cordova-android`. I get this error with `android@6`:

```
...app/platforms/android/gradlew: Command failed with exit code 1 Error output:
...app/platforms/android/res/xml/config.xml:44: AAPT: error: resource xml/network_security_config (aka io.ionic.starter:xml/network_security_config) not found.

...app/platforms/android/res/xml/config.xml:44: error: resource xml/network_security_config (aka io.ionic.starter:xml/network_security_config) not found.
error: failed linking file resources.

Failed to execute aapt
com.android.ide.common.process.ProcessException: Failed to execute aapt
```

This is simply because the app folder moved from `platforms/android` to `platforms/android/app/src/main` from 6 to 7. 

---

**The fix for this is to make sure your Cordova CLI is updated to the latest, then start a new app (or re-add the android platform).**

```
npm i -g cordova@latest
```

THEN:

```
ionic cordova platform rm android
ionic cordova platform add android
```

---

**If you plan to use `cordova-android` 6, these are the changes you'll need to make to your `config.xml`:**

```diff
     <preference name="SplashScreen" value="screen" />
     <preference name="SplashScreenDelay" value="3000" />
     <platform name="android">
-        <edit-config file="app/src/main/AndroidManifest.xml" mode="merge" target="/manifest/application" xmlns:android="http://schemas.android.com/apk/res/android">
+        <edit-config file="AndroidManifest.xml" mode="merge" target="/manifest/application" xmlns:android="http://schemas.android.com/apk/res/android">
             <application android:networkSecurityConfig="@xml/network_security_config" />
         </edit-config>
-        <resource-file src="resources/android/xml/network_security_config.xml" target="app/src/main/res/xml/network_security_config.xml" />
+        <resource-file src="resources/android/xml/network_security_config.xml" target="res/xml/network_security_config.xml" />
         <allow-intent href="market:*" />
         <icon density="ldpi" src="resources/android/icon/drawable-ldpi-icon.png" />
         <icon density="mdpi" src="resources/android/icon/drawable-mdpi-icon.png" />
```

**Comment by SivaSaiKR** [comment]
> Yes @dwieeb, resources/android/xml/network_security_config.xml has been created.
> I started new project today with these steps:
> 
> ```
> ionic start myApp sidemenu
> ionic cordova prepare android
> ```
> 
> edited config.xml widget id
> 
> run
> `ionic cordova run android`.
> And the error appeared.
> 
> P.S:
> After reporting this problem, I changed my config.xml this way:
> 
> ```
>  <edit-config file="AndroidManifest.xml" mode="merge" target="/manifest/application" xmlns:android="http://schemas.android.com/apk/res/android">
>             <application android:networkSecurityConfig="@xml/network_security_config" />
>         </edit-config>
>         <resource-file src="resources/android/xml/network_security_config.xml" target="res/xml/network_security_config.xml" />
> ```
> 
> And Successful Launch App

thank so much bro

**Comment by GodwinStanislaus** [comment]
> Uh oh!
> 
> @douglasgsouza Did the `resources/android/xml/network_security_config.xml` file get created? I'm not running into this issue with new apps. I'm using cordova-android 8.0.0 (I noticed you're on 6.3.0, could that be it?).

Yes, you are right. I updated cordova-android to cordova-android@8.0.0, and the error is gone.
Thank You

**Comment by yanqiw** [comment]
> e are the changes you'll need

this one help me, thx!!!

**Comment by bhandaribhumin** [comment]
not solve for me.
`cordova platform add android@8.0.0
Using cordova-fetch for cordova-android@8.0.0
Adding android project...
Creating Cordova project for the Android platform:
        Path: platforms/android
        Package: com.rti.campus
        Name: _RTI
        Activity: MainActivity
        Android target: android-28
Subproject Path: CordovaLib
Subproject Path: app
Android project created with cordova-android@8.0.0
Source path does not exist: resources/android/xml/network_security_config.xml
[ERROR] An error occurred while running subprocess cordova.
        
        cordova platform add android@8.0.0 exited with exit code 1.`

**Comment by Chamiyalt** [comment]
how do i fix this issue for older versions of android?

**Comment by dwieeb** [comment]
@Chamiyalt last part of [my comment](https://github.com/ionic-team/starters/issues/758#issuecomment-494501210)
