### ISSUE TITLE
Document how to test a new starter better

### ISSUE THREAD

**Issue by mraible** [ionic-team/starters#8]
In CONTRIBUTING, it says:

```
Copy the generated starter into a different directory and test it!
```

I can build my starter, cd into it in the `build` directory, and run `npm i && ionic serve` from there, but it seems like there might be a better way? Is this the best way to test a new starter?

**Comment by dwieeb** [comment]
Unfortunately yes, because starters are deployed to S3/CloudFront after they are generated. 

`ionic start` now simply downloads a `tar.gz` file. There could be a way to use `ionic start` with a starter directory, but that would have to be a CLI PR.

**Comment by mraible** [comment]
I'm attempting to test the `oktadeveloper/jhipster` starter with Travis and it fails when I try to build it:

```
> @ starters:build /home/travis/build/oktadeveloper/ionic-jhipster-starter/starters
> node ./bin/ionic-starters build "ionic-angular/community/oktadeveloper/jhipster"
module.js:545
    throw err;
    ^
Error: Cannot find module '../'
    at Function.Module._resolveFilename (module.js:543:15)
    at Function.Module._load (module.js:470:25)
    at Module.require (module.js:593:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/home/travis/build/oktadeveloper/ionic-jhipster-starter/starters/bin/ionic-starters:3:17)
    at Module._compile (module.js:649:30)
    at Object.Module._extensions..js (module.js:660:10)
    at Module.load (module.js:561:32)
    at tryModuleLoad (module.js:501:12)
    at Function.Module._load (module.js:493:3)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! @ starters:build: `node ./bin/ionic-starters build "ionic-angular/community/oktadeveloper/jhipster"`
npm ERR! Exit status 1
```

https://travis-ci.org/oktadeveloper/ionic-jhipster-starter/builds/370386112#L575

Any idea how I can test my starter in Travis? I'm open to better ways than [my current config](https://github.com/oktadeveloper/ionic-jhipster-starter/pull/9).

**Comment by dwieeb** [comment]
@mraible I left a comment in the PR you linked (looks like you already got to it). The source code for the scripts needs to be compiled from TypeScript.

Also, I haven't had time to document this much yet, but you can define scripts in your starter manifest to test ([here's an example](https://github.com/ionic-team/starters/blob/master/angular/official/blank/ionic.starter.json#L4-L11)). The `test` script gets run after the starter is built and has had its dependencies installed. You have to have a WIP PR open to this repo though. The UX for external starter developers isn't the greatest right now,  I apologize.
