### ISSUE TITLE
Unable to find starter template for oktadeveloper/jhipster

### ISSUE THREAD

**Issue by mraible** [ionic-team/starters#828]
**Starter Type:** angular
**Starter Template:** oktadeveloper/jhipster

**Description:**

The following command worked last week:

```
ionic start ionic4j oktadeveloper/jhipster
```

Now it results in:

```
[ERROR] Unable to find starter template for oktadeveloper/jhipster
```

**My `ionic info`:**

```
Ionic:

   Ionic CLI : 5.2.1

Utility:

   cordova-res : not installed
   native-run  : not installed

System:

   NodeJS : v10.16.0
   npm    : 6.9.0
   OS     : macOS Mojave
```

**Other Information:**

The last successful nightly build we had was yesterday: https://travis-ci.org/oktadeveloper/generator-jhipster-ionic/builds/555804733

I just tried re-running it and the error happens today. Here's the project's build history: https://travis-ci.org/oktadeveloper/generator-jhipster-ionic/builds

**Comment by elylucas** [comment]
Hi @mraible,

Sorry, this was an error on our side. The starter should be working again so give it a test and let us know.

**Comment by mraible** [comment]
Works now. Thanks!
