### ISSUE TITLE
angular - app.component.scss no longer global?

### ISSUE THREAD

**Issue by rtpHarry** [ionic-team/starters#865]
**Starter Type:** angular
**Starter Template:** sidemenu

**Description:**
Ok please forgive my clunkiness of asking this but I dont have better vocab for it.

What used to be the `app.scss` is now `app.component.scss`.

It was included using `angular.json` in the `styles` section, now it is automatically included by the (insert angular magic here) as a component.

However, it doesn't seem to work the same.

Before I had a css class `.highlight-row { background-color: red; }` and I could add that class to any component and it would get the styles.

Now it's wrapped up in the namespace type stuff and no longer works. It can't see that rule.

If I move the same rules to `global.scss` it works as before.

So can somebody explain if either:

1. I was using this wrong before and was just getting lucky, or
2. The comments at the top of the app.component.scss are no longer correct:

```
// App Styles
// ----------------------------------------------------------------------------
// Put style rules here that you want to apply to the entire application. These 
// styles are for the entire app and not just one component. Additionally, this 
// file can hold Sass mixins, functions, and placeholder classes to be imported 
// and used throughout the application.
```

**Comment by vincekd** [comment]
`app.component.scss` is no longer working for me either. As a workaround I am putting app-wide styling in `src/global.scss`

**Comment by mhartington** [comment]
Yes, if you want global styling, you can use the global.scss, as the name suggests.

The idea of scoping the `app.scss` to the `app.component.scss` is 2 fold.

1) Better alignment to a vanilla angular starter, which includes an `app.component.scss`
2) Scopes styles only to the app.component. 

With regards to the comment in app.component.scss, I will update this.

**Comment by rtpHarry** [comment]
This makes sense. One thing to consider though is that many tutorials have used app.scss up until now to store global styles. It could cause some confusion for people following older tutorials.

I don't know what the exact rules for a breaking change are but maybe putting a note in the updated comment that you should use global.scss for app-wide styles would save a lot of newbie headaches?
