### ISSUE TITLE
Download and extracting is not working

### ISSUE THREAD

**Issue by mraible** [ionic-team/starters#942]
**Starter Type:** angular
**Starter Template:** all

**Description:**

After upgrading to Ionic CLI 5.4.1, download and extraction of starters is no longer working. I tried with 5.1.0 before I upgraded and it worked fine. After upgrading and downgrading back to 5.1.0, the problem persists.

**My `ionic info`:**

```
$ ionic start foo tabs --verbose
  ionic:lib Terminal info: { ci: false, shell: '/bin/zsh', tty: true, windows: false } +0ms
  ionic:lib CLI global options: { _: [ 'start', 'foo', 'tabs' ], help: null, h: null, verbose: true, quiet: null, interactive: true, color: true, confirm: null, json: null, project: null, '--': [] } +4ms
  ionic Context: { binPath: '/usr/local/lib/node_modules/ionic/bin/ionic', libPath: '/usr/local/lib/node_modules/ionic', execPath: '/Users/mraible', version: '5.1.0' } +0ms
  ionic:lib:telemetry Sending telemetry for command: 'ionic start' [
  ionic:lib:telemetry   'foo',
  ionic:lib:telemetry   'tabs',
  ionic:lib:telemetry   '--verbose',
  ionic:lib:telemetry   '--interactive',
  ionic:lib:telemetry   '--color',
  ionic:lib:telemetry   '--project-id=foo'
  ionic:lib:telemetry ] +0ms
✔ Preparing directory ./foo - done!
  ionic:commands:start Tar extraction created for /Users/mraible/foo +0ms
  superagent GET https://d2ql0qc7j8u4b2.cloudfront.net/angular-official-tabs.tar.gz +0ms
⠸ Downloading and extracting tabs starter
⠼ Downloading and extracting tabs starter (100.00%)f
```

Posted to the Ionic Forums as well: https://forum.ionicframework.com/t/starters-not-working/173988

**Comment by mraible** [comment]
Thanks for confirming @hfournier! I see it in my Travis builds too.

**Comment by hfournier** [comment]
I'm still having the same issue today.

**Comment by GinatheDog** [comment]
I am also having the same issue.  You closed it to early

thomass-MacBook-Pro:tesrt davemolin$ ionic start apptest blank

Pick a framework! 😁

Please select the JavaScript framework to use for your new app. To bypass this
prompt next time, supply a value for the --type option.

? Framework: Angular
✔ Preparing directory ./apptest - done!
thomass-MacBook-Pro:tesrt davemolin$ ionic start IonicBlankApp blank --type=angular --verbose
  ionic:lib Terminal info: { ci: false, shell: '/bin/bash', tty: true, windows: false } +0ms
  ionic:lib CLI global options: { _: [ 'start', 'IonicBlankApp', 'blank' ], help: null, h: null, verbose: true, quiet: null, interactive: true, color: true, confirm: null, json: null, type: 'angular', project: null, '--': [] } +3ms
  ionic Context: { binPath: '/usr/local/lib/node_modules/ionic/bin/ionic', libPath: '/usr/local/lib/node_modules/ionic', execPath: '/Users/davemolin/tesrt', version: '5.4.1' } +0ms
  ionic:lib:telemetry Sending telemetry for command: 'ionic start' [ 'IonicBlankApp',
  ionic:lib:telemetry   'blank',
  ionic:lib:telemetry   '--verbose',
  ionic:lib:telemetry   '--interactive',
  ionic:lib:telemetry   '--color',
  ionic:lib:telemetry   '--type=angular',
  ionic:lib:telemetry   '--project-id=IonicBlankApp' ] +0ms
✔ Preparing directory ./IonicBlankApp - done!
  ionic:commands:start Tar extraction created for /Users/davemolin/tesrt/IonicBlankApp +0ms
  superagent GET https://d2ql0qc7j8u4b2.cloudfront.net/angular-official-blank.tar.gz +0ms
⠸ Downloading and extracting blank starter 
⠋ Downloading and extracting blank starter (100.00%)

**Comment by mraible** [comment]
I'll reopen the issue. Another problem I'm experiencing is the latest `master` branch code is not the latest on CloudFront. I believe it's caused by [this failed build](https://circleci.com/gh/ionic-team/starters/9213). Any ideas @dwieeb @mhartington?

**Comment by mhartington** [comment]
For those who are stuck at "100.00%" status, please see this comment.

https://github.com/ionic-team/ionic-cli/issues/4158#issuecomment-534498792
